config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :users
    resources :contacts

    root to: "users#index"
  end

  get 'static/home'
  root to: 'static#home'
  devise_for :users
  resources :contacts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates_presence_of :name, :address, :email, :phone

  belongs_to :user

  EMAIL_REGEX = /\A\S+@.+\.\S+\z/

  validates_format_of :email, with: EMAIL_REGEX 

  PHONE_REGEX = /\A[0-9]*\Z/

  validates_format_of :phone, with: PHONE_REGEX

  validates :phone, length: { is: 10 } 
  
  scope :sort_by_name, -> { order('name ASC') }
end

app/models/user.rb
class User < ApplicationRecord
  ############################################################################################
  ## PeterGate Roles                                                                        ##
  ## The :user role is added by default and shouldn't be included in this list.             ##
  ## The :root_admin can access any page regardless of access settings. Use with caution!   ##
  ## The multiple option can be set to true if you need users to have multiple roles.       ##
  petergate(roles: [:admin], multiple: false)                                      ##
  ############################################################################################ 
 

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :contacts
end

app/controllers/admin/application_controller.rb
# All Administrate controllers inherit from this `Admin::ApplicationController`,
# making it the ideal place to put authentication logic or other
# before_actions.
#
# If you want to add pagination or other controller-level concerns,
# you're free to overwrite the RESTful controller actions.
module Admin
  class ApplicationController < Administrate::ApplicationController
    before_action :authenticate_admin

    def authenticate_admin
      # TODO Add authentication logic here.
    end

    # Override this value to specify the number of elements to display at a time
    # on index pages. Defaults to 20.
    # def records_per_page
    #   params[:per_page] || 20
    # end
  end
end

app/controllers/admin/contacts_controller.rb
module Admin
  class ContactsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Contact.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Contact.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = User.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   User.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  before_action :authorize_user, only: [:update, :edit, :destroy]

  access all: [:show, :index], user: [:edit, :update, :destroy, :new, :create], admin: :all


  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.sort_by_name
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)
    @contact.user_id = current_user.id
    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    if @auth 
      respond_to do |format|
        if @contact.update(contact_params)
          format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
          format.json { render :show, status: :ok, location: @contact }
        else
          format.html { render :edit }
          format.json { render json: @contact.errors, status: :unprocessable_entity }
        end
      end
    else 
      redirect_to contacts_path, notice: "You are not authorized"
    end 
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    if @auth
      @contact.destroy
      respond_to do |format|
        format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
        format.json { head :no_content }
      end 
    else 
      redirect_to contacts_path, notice: "You are not authorized"
    end 
  end



  private
    # Use callbacks to share common setup or constraints between actions.
   
    def authorize_user
      @auth = current_user.id == @contact.user_id || current_user.roles == [:admin, :user]
    end


    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:name, :address, :email, :phone)
    end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def admin_dash user
    if logged_in?(:admin)
      (link_to "Admin Dashboard", admin_root_path)
    end 
  end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/contacts/_form.html.erb
<%= form_with(model: contact, local: true) do |form| %>

  <% if contact.errors.any? %>
    <% contact.errors.full_messages.each do |error| %>
      <%= js add_gritter(error, title: "Error", sticky: false) %>
    <% end %>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :contact_name, placeholder: "John Doe" %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address, id: :contact_address, placeholder: "1600 Pennsylvania Ave NW Washington, DC 20500" %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :contact_email, placeholder: "johndoe@example.com" %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone, id: :contact_phone, placeholder: "2024561111" %>
  </div>

  <div class="actions">
    <%= form.submit "Submit", class: "waves-effect waves-light btn" %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<div class="container">
  <h1>Editing Contact</h1>

  <%= render 'form', contact: @contact %>

  <%= link_to 'Show', @contact, class: "waves-effect waves-light btn btn-space" %> 
  <%= link_to 'Back', contacts_path, class: "waves-effect waves-light btn btn-space" %>
</div>  

app/views/contacts/index.html.erb
<div class="container">

  <h1>Contacts</h1>

  <table class="highlight">
    <thead>
      <tr>
        <th>Name</th>
        <th>Address</th>
        <th>Email</th>
        <th>Phone</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @contacts.each do |contact| %>
        <tr>
          <td><%= contact.name %></td>
          <td><%= contact.address %></td>
          <td><%= contact.email %></td>
          <td><%= contact.phone %></td>
          <td><%= link_to '<i class="material-icons">pageview</i>'.html_safe, contact, class: 'index-icons' %></td>
          <% if  %>  
            <td><%= link_to '<i class="material-icons">edit</i>'.html_safe, edit_contact_path(contact), class: 'index-icons'%></td>
          <% end %>
            <td><%= link_to '<i class="material-icons">delete</i>'.html_safe, contact, method: :delete, data: { confirm: 'Are you sure?' }, class: 'index-icons' %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Contact', new_contact_path, class: "waves-effect waves-light btn" %>
</div>

app/views/contacts/new.html.erb
<div class="container">
  <h1>New Contact</h1>

  <%= render 'form', contact: @contact %>

  <%= link_to 'Back', contacts_path, class: "waves-effect waves-light btn btn-space" %>
</div>  

app/views/contacts/show.html.erb
<div class="container">

  <div class="row">
    <div class="col s12 m12 l12 xl12 center">
      <div class="card z-depth-5">
        <div class="card-content black-text">
          <span class="card-title">Card Title</span>
            <p>
              <strong>Name:</strong>
              <%= @contact.name %>
            </p>

            <p>
              <strong>Address:</strong>
              <%= @contact.address %>
            </p>

            <p>
              <strong>Email:</strong>
              <%= @contact.email %>
            </p>

            <p>
              <strong>Phone:</strong>
              <%= @contact.phone %>
            </p>
        </div>
        <div class="card-action">
          <a href="#"><%= link_to 'Edit', edit_contact_path(@contact), class: "waves-effect waves-light btn" %></a>
          <a href="#"><%= link_to 'Back', contacts_path, class: "waves-effect waves-light btn" %></a>
        </div>
      </div>
    </div>
  </div>
</div>  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AddressBook</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/nav' %>
    <%= js add_gritter(flash[:notice], :title => "Notice!", :sticky => false, :time => 1000) %>
    <%= js add_gritter(flash[:alert], :title => "Alert!", :sticky => false, :time => 1000) %>
    <%= js add_gritter(flash[:error], :title => "Error!", :sticky => false, :time => 1000) %>
    <%= yield %>
  </body>
</html>

app/views/shared/_nav.html.erb
<nav>
  <div class="nav-wrapper blue-grey darken-4">
    <a href="#!" class="brand-logo"><%= link_to(image_tag('bookly.png', size: '220x75', class: "responsive-img"), root_path) %></a>
    <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
    <ul class="right hide-on-med-and-down">
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "Contacts", contacts_path %></li>
      <li><%= admin_dash(current_user) %></li>
      <% if current_user %>
        <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
      <% else %>
        <li><%= link_to "Register", new_user_registration_path %></li>
        <li><%= link_to "Sign In", new_user_session_path %></li>
      <% end %>

    </ul>
    <ul class="side-nav" id="mobile-demo">
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "Contacts", contacts_path %></li>
      <li><%= admin_dash(current_user) %></li>
      <% if current_user %>
        <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
      <% else %>
        <li><%= link_to "Register", new_user_registration_path %></li>
        <li><%= link_to "Sign In", new_user_session_path %></li>
      <% end %>
    </ul>
  </div>
</nav>